# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ldz0moPT6qbqMzt6HV_OUbj-rKxFvM6q
"""

# Commented out IPython magic to ensure Python compatibility.
# 데이터 가져오기
# drive에 연결
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
# 현재 데이터가 있는 공간으로 작업 경로를 변경
# %cd "/content/drive/MyDrive/Colab Notebooks"

# pandas 패키지 별칭 pd라는 별칭으로 불러오기
import pandas as pd

# sample_submission.csv 파일을 submission 이라는 변수에 할당
submission = pd.read_csv("sample_submission.csv")  # 제출파일

# pandas 내에 있는 read_csv 함수를 사용해
# train.csv , test.csv 파일을 각각 train , test 라는 이름으로 불러오기
train = pd.read_csv('train.csv')
test  = pd.read_csv('test.csv')

submission.head()  # 0 , 1 , 2 다중클래스 잘되었는지 확인

# train 데이터 하위 행 5개 확인
train.tail()

# train 데이터들의 컬럼 확인 , feature 확인
train.columns

# train 데이터의 행과 열의 개수 확인
train.shape

# train 데이터프레임의 정보 확인, 데이터 분포를 봐야함. 무작정 코드 실행하면 안됨.
train.info()

# train 데이터의 기초 통계량을 간략하게 확인(개수, 표준편차 등)
train.describe()

# 각 변수들을 날짜 단위가 아닌 연 단위 (만 나이)로 바꿔보기(begin_month 제외)
train.loc[train["DAYS_EMPLOYED"] > 0, "DAYS_EMPLOYED"] = 0  # 0 보다 큰경우 0
train["DAYS_BIRTH"]    = (train["DAYS_BIRTH"]    * -1) / 365.0
train["DAYS_EMPLOYED"] = (train["DAYS_EMPLOYED"] * -1) / 365.0
train["begin_month"]   =  train["begin_month"]   * -1

# 동일하게 해줘야 함
test.loc[test["DAYS_EMPLOYED"] > 0, "DAYS_EMPLOYED"] = 0
test["DAYS_BIRTH"]    = (test["DAYS_BIRTH"]    * -1) / 365.0
test["DAYS_EMPLOYED"] = (test["DAYS_EMPLOYED"] * -1) / 365.0
test["begin_month"]   =  test["begin_month"]   * -1

# train 데이터의 카테고리 컬럼들을 추출
categories = train.select_dtypes(exclude='number')

# 추출한 변수들의 값들의 비율을 확인
for feature in categories:  # 모든 피처에 대해서
    print(train[feature].value_counts(normalize=True))
    # 직업, 거주타입 ,결혼여부, 차 소유, 카드 발급여부 등
    # 결측치 있는데 데이터있음
    print('-' * 50)

# train 데이터의 'occyp_type' 변수의 결측치들을 "No job"으로 채우기
train["occyp_type"] = train["occyp_type"].fillna("No job")
test["occyp_type"]  = test["occyp_type"].fillna("No job")

occyp_order = train['occyp_type'].value_counts().sort_values(ascending=False).index.tolist()

train.to_csv("train_processed.csv", index=False)

# occyp_type 변수의 값의 비율을 백분율로 확인  # 결측치 No job 30.88
round(train["occyp_type"].value_counts(normalize=True) * 100, 2)

# 모델링
# credit 변수 돌리기
# 신용등급 2, 1, 0
train["credit"].value_counts()

# 전처리된 train, test 데이터를 각각 저장해주기
# x: 독립변수(원인) y: 종속변수(결과)
train.to_csv("train_processed.csv", index=False)
test.to_csv("test_processed.csv",   index=False)

from sklearn.tree import DecisionTreeClassifier  # 지니불순도 , 가지치기 해나갈 것.

# sklearn 패키지의 tree 모듈에서 DecisionTreeClassifier 객체를 불러옴
from sklearn.tree import DecisionTreeClassifier

# model 이라는 변수에 DecisionTreeClassifier 객체를 할당
model = DecisionTreeClassifier(random_state=42)

print(train['occyp_type'].head())

# sklearn 패키지의 preprocessing 모듈에서 LabelEncoder 함수를 불러오기
from sklearn.preprocessing import LabelEncoder

# le라는 변수에 LabelEncoder 인스턴스를 할당
le = LabelEncoder()

# LabelEncoder로 object 타입 변수들을 수치형 데이터로 변환
cols = train.select_dtypes(include=['object']).columns

# 전부 수치형 데이터로 바꿔주기
# ★ 수정: train fit → test transform (인코딩 불일치 방지)
for col in cols:
    le.fit(train[col])
    train[col] = le.transform(train[col])
    test[col]  = test[col].apply(lambda x: x if x in le.classes_ else le.classes_[0])
    test[col]  = le.transform(test[col])

# 변환결과를 확인, 문자를 찾아볼 수 없다. (정규화를 시킨다던지. 전처리 스타일)
train.head()

# train 데이터를 독립변수 X 와 종속변수 y로 나눠줌
X = train.drop(columns="credit")  # credit drop시킴, 원본 손상 없음
y = train["credit"]                # y에 값을 넣기

# sklearn 패키지의 train_test_split 함수를 불러옴
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

# model 학습을 진행
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score  # 정확도

y_pred = model.predict(X_valid)
acc    = accuracy_score(y_valid, y_pred)
print(f"Accuracy : {round(acc, 4)}")  # 100명중 58

from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_valid)
cm     = confusion_matrix(y_valid, y_pred, labels=[0, 1, 2])
print(cm)
# 혼동행렬 0 1 2 row , col 0,1,2

pred = model.predict_proba(test)
submission.iloc[:, 1:] = pred
submission

# 1에 저장
submission.to_csv("submission1.csv", index=False)

# matplotlib.pyplot을 별칭 plt로 불러옴
import matplotlib.pyplot as plt

# seaborn을 별칭 sns 로 불러와
import seaborn as sns

rc = {
    "axes.facecolor":   "#F6F6F6",
    "figure.facecolor": "#B8B8B8",
    "axes.edgecolor":   "#000000",
    "grid.color":       "#C4C4C4",
    "axes.labelcolor":  "#000000",
    "xtick.color":      "#000000",
    "ytick.color":      "#000000",
    "grid.alpha":       0.4
}
sns.set(rc=rc)

sns.countplot(train, x="credit")

print(train.dtypes)

# FLAG_MOBIL, work_phone, phone, email 의 타입을 바꿔줌
train['FLAG_MOBIL'] = train['FLAG_MOBIL'].astype('object')
train['work_phone'] = train['work_phone'].astype('object')
train['phone']      = train['phone'].astype('object')
train['email']      = train['email'].astype('object')

# pandas 가 csv 파일에서 타입을 자동으로 판단하는 부분을 수동으로.
# 0,1 을 int64로 읽음. 수치형이 아닌 카테고리임을 알려줌
cat_cols = ['gender', 'car', 'reality', 'income_type', 'edu_type',
            'family_type', 'house_type', 'occyp_type']
for col in cat_cols:
    train[col] = train[col].astype('object')

# 수치형, 카테고리 정보 넘김
train_num = train.select_dtypes(include="number").copy()
train_num["credit"] = train["credit"]

train_cat = train.select_dtypes(exclude="number").copy()
train_cat["credit"] = train["credit"]

train_num.describe()

# Seaborn, Matplotlib → plotly 시각화 툴 변경
import plotly.express as px
from plotly.subplots import make_subplots
import math

# 1. 컬럼 개수에 따라 필요한 행(rows) 수 자동 계산
num_eda_cols = train_num.columns[:-1]
n_cols = 2
n_rows = math.ceil(len(num_eda_cols) / n_cols)  # 예: 컬럼 9개면 5행 생성

# 2. 서브플롯 틀 만들기
fig = make_subplots(
    rows=n_rows, cols=n_cols,
    subplot_titles=num_eda_cols,
    vertical_spacing=0.05  # 위아래 간격 살짝 조정
)

# 색상 매핑
color_map = {0: "#FA5858", 1: "#2EFE2E", 2: "#0040FF"}

# 3. 반복문으로 그리기
for i, col in enumerate(num_eda_cols):
    r = (i // n_cols) + 1
    c = (i %  n_cols) + 1

    sub_fig = px.box(train_num, x="credit", y=col,
                     color="credit", color_discrete_map=color_map,
                     category_orders={"credit": [0, 1, 2]})

    for trace in sub_fig.data:
        trace.showlegend = (i == 0)
        fig.add_trace(trace, row=r, col=c)

# 4. 레이아웃 조정
fig.update_layout(
    height=400 * n_rows, width=1000,
    title_text="< Credit Distribution (Interactive Plotly) >",
    title_x=0.5, showlegend=True
)
fig.show()

print(train[['DAYS_BIRTH', 'DAYS_EMPLOYED', 'begin_month']].head())

# 추출한 상관관계를 바탕으로 heatmap을 그리기
plt.figure(figsize=(10, 10))
sns.heatmap(train_num.corr(), cmap='coolwarm', annot=True, fmt='.2f', linewidths=1, cbar=False)
plt.xticks(rotation=45)
plt.title("< Correlation with Numerical Variables >", pad=20, fontsize=20)
plt.show()

# train_num 데이터로 변수들 간의 상관관계를 더 자세히 확인
color = ["#FA5858", "#2EFE2E", "#0040FF"]
sns.pairplot(train_num, hue="credit", markers=["o", "s", "D"], palette=color)

# category columns EDA (without 'occup_type')
cat_EDA_cols = train_cat.columns[:-2]
fig, axes = plt.subplots(nrows=6, ncols=2, figsize=(30, 36))
axes = axes.flatten()

for i, col in enumerate(cat_EDA_cols):
    ax = axes[i]
    sorted_col = train_cat[col].value_counts().sort_values(ascending=False).index
    train_cat[col] = pd.Categorical(train_cat[col], sorted_col)
    sns.histplot(data=train_cat, x=col, binwidth=0.5, shrink=0.5,
                 ax=ax, multiple="dodge")
    ax.set_title(f"Credit Distribution ({col.upper()})", fontsize=20)
    ax.set_ylabel("")
    ax.set_xlabel("")

plt.suptitle("\n< Credit Distribution for Object Columns >", fontsize=50)
plt.show()

# 변수 occyp_type을 내림차순으로 정리
sorted_col = train_cat["occyp_type"].value_counts().sort_values(ascending=False).index
train_cat["occyp_type"] = pd.Categorical(train_cat["occyp_type"], sorted_col)

# 이진 데이터와 나머지 데이터로 나누기
bin_cols = ["gender", "car", "reality", "FLAG_MOBIL", "work_phone", "phone", "email"]
train_cat_bin  = train_cat[bin_cols].copy()
train_cat_bin["credit"] = train_cat["credit"]
train_cat_over = train_cat.drop(columns=bin_cols)

# binary category columns EDA
cat_EDA_cols = train_cat_bin.columns[:-1]
fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(16, 24))
axes = axes.flatten()

for i, col in enumerate(cat_EDA_cols):
    ax = axes[i]
    sns.histplot(data=train_cat_bin, x=col, hue="credit",
                 binwidth=0.5, shrink=0.5,
                 palette=color, ax=ax,
                 multiple="dodge", hue_order=[0, 1, 2])
    ax.set_title(f"Credit Distribution ({col.upper()})", fontsize=20)
    ax.set_ylabel("")
    ax.set_xlabel("")

plt.suptitle("\n< Credit Distribution for Object Columns >", fontsize=50)
plt.show()

# 시각화는 다 plotly 로 심플하게 실습
ratio = train_cat_over["income_type"].value_counts()
labels = train_cat_over["income_type"].unique().categories
wedgeprops = {'width': 0.7, 'edgecolor': 'w', 'linewidth': 5}
plt.title("< income_type >")
plt.pie(x=ratio, labels=labels, autopct="%.2f%%", wedgeprops=wedgeprops)
plt.show()

fig, axes = plt.subplots(3, 2, figsize=(12, 18))
axes = axes.flatten()
columns = train_cat_over.columns[:-1]

for i, col in enumerate(columns):
    ratio  = train_cat_over[col].value_counts()
    labels = train_cat_over[col].unique().categories
    wedgeprops = {'width': 0.7, 'edgecolor': 'w', 'linewidth': 5}
    axes[i].set_title(f"< {col} >")
    axes[i].pie(x=ratio, labels=labels, autopct="%.2f%%", wedgeprops=wedgeprops)

plt.show()

plt.figure(figsize=(18, 8))
sns.histplot(data=train_cat_over, x="occyp_type",
             binwidth=0.5, shrink=0.5, color="blue")
plt.xticks([])
plt.text(x=len(sorted_col) / 2 + 6.5, y=250,
         s='\n'.join(sorted_col.astype(str)),
         fontsize=9, ha='center',
         bbox=dict(facecolor='white', edgecolor='black', boxstyle='round,pad=0.5'))
plt.title("< Occyp_type >", pad=30, fontsize=20)
plt.show()

plt.figure(figsize=(18, 8))
sns.histplot(data=train_cat_over, x="occyp_type", binwidth=0.5, shrink=0.5, color="blue")
plt.xticks([])
plt.text(x=len(sorted_col) // 2 + 6.5, y=250,
         s='\n\n'.join(sorted_col.astype(str)), fontsize=9,
         ha='center', bbox=dict(facecolor='white', edgecolor='black', boxstyle='round,pad=0.5'))
plt.title('\n<Occyp_type', pad=30, fontsize=20)
plt.show()

print(train['occyp_type'].head())

# tabulate 모듈을 설치합니다
# 표형태로 나오는, 공식문서참조
!pip install tabulate
from tabulate import tabulate

output_table = []
occypys = train_cat_over['occyp_type'].value_counts().index
dfs = [train_cat_over[train_cat_over['occyp_type'] == occypys[i]]
       for i in range(len(occypys))]

for i, df in enumerate(dfs):
    output_table.append(
        [occypys[i],
         f"{round(len(df) / len(train_cat_over) * 100, 2)}%",
         round(df['credit'].value_counts(normalize=True) * 100, 2).astype("str") + "%"]
    )

print(tabulate(output_table,
               headers=['Occyp Type', 'Proportion', 'Credit Distribution'],
               tablefmt='grid'))

"""### 피처 엔지니어링 (원본을 그대로 쓰는게 맞는지) good fit 에 맞추기 위해"""

import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew, kurtosis

# income_total, DAYS_EMPLOYED 변수의 히스토그램을 그립니다
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes = axes.flatten()
columns = ["income_total", "DAYS_EMPLOYED"]

for i, col in enumerate(columns):
    sns.histplot(data=train, x=col, ax=axes[i])
    axes[i].set_title(f"< {col} >")

plt.show()
# 스큐니스 0

# kurtosis 값 확인, 산포도 ~3 에 가까워지면 노말
# ~3보다 작으면 얇다
# 크면 정규분포보다 두껍게

fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes = axes.flatten()
columns = ["income_total", "DAYS_EMPLOYED"]

for i, col in enumerate(columns):
    sns.histplot(data=train, x=col, ax=axes[i])
    axes[i].set_title(f"< {col} >")
    skewness = skew(train[col])
    kurto    = kurtosis(train[col], fisher=False)
    axes[i].set_xlabel(
        f"skewness: {round(skewness, 2)}\nkurtosis: {round(kurto, 2)}"
    )

plt.show()

import numpy as np

fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes = axes.flatten()
columns = ["income_total", "DAYS_EMPLOYED"]

# 로그 변환 정규화
for i, col in enumerate(columns):
    if i == 1:
        data = np.log(train[col] + 1)
    else:
        data = np.log(train[col])
    sns.histplot(data=data, ax=axes[i])
    axes[i].set_title(f"< {col} >")
    skewness = skew(data)
    kurto    = kurtosis(data, fisher=False)
    axes[i].set_xlabel(
        f"skewness: {round(skewness, 2)}\nkurtosis: {round(kurto, 2)}"
    )

plt.show()

# test 데이터 로그 변환
test["income_total"]  = np.log(test["income_total"])
test["DAYS_EMPLOYED"] = np.log(test["DAYS_EMPLOYED"] + 1)

# train 데이터도 로그 변환
train["income_total"]  = np.log(train["income_total"])
train["DAYS_EMPLOYED"] = np.log(train["DAYS_EMPLOYED"] + 1)

# test 데이터에 "child_num_over_five" / 자식 5명 이상 자녀
test["child_num_over_five"]  = (test["child_num"]  > 5).astype(int)
train["child_num_over_five"] = (train["child_num"] > 5).astype(int)

# train 중복 행 확인
train.drop(columns="begin_month").duplicated().sum()

# test 중복 행 확인
test.drop(columns="begin_month").duplicated().sum()

# 신용카드 중복 개수 duplicated_num 변수 추가
train_drop = train.drop(columns="begin_month")
duplicated_num = train_drop.groupby(
    train_drop.columns.tolist(),
    as_index=False
).transform("size")
train["duplicated_num"] = duplicated_num
train.head()

test_drop = test.drop(columns="begin_month")
duplicated_num = test_drop.groupby(
    test_drop.columns.tolist(),
    as_index=False
).transform("size")
test["duplicated_num"] = duplicated_num

# before_employed 변수 추가
train["before_employed"] = train["DAYS_BIRTH"] - train["DAYS_EMPLOYED"]
test["before_employed"]  = test["DAYS_BIRTH"]  - test["DAYS_EMPLOYED"]

from tabulate import tabulate

output_table = []
types = train["house_type"].value_counts().index
dfs   = [train[train["house_type"] == types[i]] for i in range(len(types))]

for i, df in enumerate(dfs):
    output_table.append(
        [types[i],
         f"{round(len(df)/len(train)*100, 2)}%",
         round(df["credit"].value_counts(normalize=True)*100, 2).astype("str") + "%"]
    )

print(tabulate(
    output_table,
    headers=["House Type", "Proportion", "Credit Distribution"],
    tablefmt="grid"
))

# house_owner 집주인이냐 아니냐
train["house_owner"] = (train["house_type"] != "Rented apartment").astype(int)
test["house_owner"]  = (test["house_type"]  != "Rented apartment").astype(int)

# 레이블 인코딩 방법 vs one hot encoding (많을수록 차원이 늘어남.)

from sklearn.preprocessing import LabelEncoder

cols = train.select_dtypes(include=["object"]).columns
le   = LabelEncoder()

for col in cols:
    le.fit(train[col])
    train[col] = le.transform(train[col])
    test[col]  = test[col].apply(lambda x: x if x in le.classes_ else le.classes_[0])
    test[col]  = le.transform(test[col])

# 저장
train.to_csv("train_processed.csv", index=False)
test.to_csv("test_processed.csv",   index=False)

"""### 하이퍼 파라미터 튜닝 및 최종 모델링"""

train      = pd.read_csv("train_processed.csv")
test       = pd.read_csv("test_processed.csv")
submission = pd.read_csv("sample_submission.csv")

print(train["credit"].value_counts())

# 앙상블 모델 보팅. 투표 > 다수결(하드보팅) 소프트 보팅(평균)
# 배깅 > 병렬 수행 (부트스트랩 모델) 랜덤포레스트 알고리즘 parallel
# 부스팅 (강화해나가는 방법)

X = train.drop(columns="credit")
y = train["credit"]

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y,
    stratify=y,
    test_size=0.2,
    random_state=42
)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

from sklearn.metrics import (
    confusion_matrix, accuracy_score,
    recall_score, precision_score,
    f1_score, log_loss
)

pred_1 = dt.predict(X_valid)

valid_cm_1        = confusion_matrix(y_valid, pred_1)
valid_acc_1       = accuracy_score(y_valid, pred_1)
valid_recall_1    = recall_score(y_valid, pred_1, average="weighted")
valid_precision_1 = precision_score(y_valid, pred_1, average="weighted")
valid_f1_1        = f1_score(y_valid, pred_1, average="weighted")

print("Confusion Matrix(혼동행렬):\n", valid_cm_1)
print()
print("Accuracy(정확도):",  round(valid_acc_1*100, 2))
print("Recall(재현율):",    round(valid_recall_1*100, 2))
print("Precision(정밀도):", round(valid_precision_1*100, 2))
print("F1 Score:",          round(valid_f1_1, 4))

from sklearn.metrics import classification_report

# 지수가중 평균
# y_valid는 실제 레이블, pred_1은 모델 예측 결과
report = classification_report(y_valid, pred_1)
print(report)

# Commented out IPython magic to ensure Python compatibility.
# 어떤 중요도를 가져오나
feature_importances = pd.Series(
    dt.feature_importances_,
    index=X_valid.columns
).sort_values(ascending=False)
feature_importance = feature_importances.head(20)
print(feature_importance)

# 시각화
# %matplotlib inline
plt.figure(figsize=(8, 6))
plt.title("Feature Importance Plot")
sns.barplot(x=feature_importance, y=feature_importance.index)
plt.show()

# 예측확률
prob_1     = dt.predict_proba(X_valid)
log_loss_1 = log_loss(y_valid, prob_1)
print("Log loss(로그 손실):", round(log_loss_1, 4))

# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

# 학습
rf.fit(X_train, y_train)

# 예측
pred_2 = rf.predict(X_valid)

# 정확도 평가
accuracy = accuracy_score(y_valid, pred_2)
print(f"RandomForestClassifier 정확도: {accuracy:.4f}")

# 오차행렬
cm2 = confusion_matrix(y_valid, pred_2)
print(cm2)

pred_2 = rf.predict(X_valid)

valid_cm_2        = confusion_matrix(y_valid, pred_2)
valid_acc_2       = accuracy_score(y_valid, pred_2)
valid_recall_2    = recall_score(y_valid, pred_2, average="weighted")
valid_precision_2 = precision_score(y_valid, pred_2, average="weighted")
valid_f1_2        = f1_score(y_valid, pred_2, average="weighted")

print("Confusion Matrix(혼동행렬):\n", valid_cm_2)
print()
print("Accuracy(정확도):",  round(valid_acc_2*100, 2))
print("Recall(재현율):",    round(valid_recall_2*100, 2))
print("Precision(정밀도):", round(valid_precision_2*100, 2))
print("F1 Score:",          round(valid_f1_2, 4))

# 변수 중요도 계산
importances_values = pd.Series(
    rf.feature_importances_,
    index=X_valid.columns
).sort_values(ascending=False)
rf_top20 = importances_values.head(20)
rf_top20

plt.figure(figsize=(8, 6))
plt.title("Feature Importances Top 20")
sns.barplot(x=rf_top20, y=rf_top20.index)
plt.show()
# 로그 로스값 뽑아보기 (배깅을 써 줄어듬 확인)

# xgboost 사용
from xgboost import XGBClassifier

xgb = XGBClassifier(random_state=42)  # verbose=1

# 학습
xgb.fit(X_train, y_train)

# 예측
pred_3 = xgb.predict(X_valid)

# 정확도
accuracy = accuracy_score(y_valid, pred_3)
print(f"XGBoost 정확도: {accuracy:.4f}")

# 혼동행렬
cm3 = confusion_matrix(y_valid, pred_3)
print(cm3)

pred_3 = xgb.predict(X_valid)

valid_cm_3        = confusion_matrix(y_valid, pred_3)
valid_acc_3       = accuracy_score(y_valid, pred_3)
valid_recall_3    = recall_score(y_valid, pred_3, average="weighted")
valid_precision_3 = precision_score(y_valid, pred_3, average="weighted")
valid_f1_3        = f1_score(y_valid, pred_3, average="weighted")

print("Confusion Matrix(혼동행렬):\n", valid_cm_3)
print()
print("Accuracy(정확도):",  round(valid_acc_3*100, 2))
print("Recall(재현율):",    round(valid_recall_3*100, 2))
print("Precision(정밀도):", round(valid_precision_3*100, 2))
print("F1 Score:",          round(valid_f1_3, 4))


# ---------------------------
# Voting Ensemble 모델
# ---------------------------

from sklearn.ensemble import VotingClassifier

# Voting 모델 생성
voting = VotingClassifier(
    estimators=[
        ('dt', dt),
        ('rf', rf),
        ('xgb', xgb)
    ],
    voting='soft'  # 확률 평균 방식
)

# 모델 학습
voting.fit(X_train, y_train)

# 예측
pred_v = voting.predict(X_valid)

# 성능 평가
from sklearn.metrics import accuracy_score

voting_acc = accuracy_score(y_valid, pred_v)

print("Voting Accuracy :", round(voting_acc, 4))


# 제출 파일 생성 (RandomForest 기준)
pred_test = rf.predict_proba(test)
submission = submission.astype(float)
submission.iloc[:, 1:] = pred_test
submission.to_csv("submission_rf.csv", index=False)
print("제출 파일 저장 완료: submission_rf.csv")
submission.head()
