# -*- coding: utf-8 -*-
"""travel_pipeline_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPfuJPrgPZ2K5spsjqS1tyNIjyJGwXCS

# 여행 상품 구매 예측
**목표**: 고객 정보로 여행 상품을 살지 안 살지 예측하기  

https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction

**데이터**: Travel.csv (4,888명, 변수 20개)

---
```
1단계. 패키지 설치 & 데이터 불러오기
2단계. 데이터 살펴보기 (EDA)
3단계. 전처리 + 학습/테스트 분리
4단계. 3가지 모델 학습 & 성능 비교
5단계. 최적 모델 상세 분석
6단계. 모델 저장 & 새 고객 예측
```
"""

# 라이브러리 설치 (LGBM, plotly)
!pip install -q lightgbm plotly

# 데이터 처리
import pandas as pd, numpy as np, pickle, warnings

# 불필요한 경고 숨기기
warnings.filterwarnings('ignore')


# 라이브러리 호출

# 로지스틱 회귀 : 기본 분류 모델
from sklearn.linear_model import LogisticRegression
# 랜덤포레스트 : 여러개의 트리를 사용하는 앙상블 모델
from sklearn.ensemble import RandomForestClassifier
# LightGBM : 부스팅 계열 분류 모델
from lightgbm import LGBMClassifier

# 평가 성능 지표
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve

# 데이터 분할
from sklearn.model_selection import train_test_split

# 시각화
import plotly.express as px
import plotly.graph_objects as go

# 전처리 파이프라인 구성
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# 결측치 처리 / 인코딩 / 스케일링
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# 구글드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# CSV 파일 불러오기
df = pd.read_csv('/content/drive/MyDrive/Travel.csv')

# 데이터 크기와 샘플 확인
print(f'데이터 크기: {df.shape[0]}명 x {df.shape[1]}개 변수')
display(df.head(3))  # 상위 3개 행 확인

import os
print(os.listdir('/content/drive/MyDrive'))

"""---
## 2단계. 데이터 살펴보기 (EDA)

결측치, 구매 비율, 직업별 구매 패턴을 시각화합니다.
"""

# 결측치 개수 확인
# 비어있는 부분이 있다면 , 에러가 날 수 있다.
# 나이가 비어있다 던지 (NaN등..) 비어있는 값을 채워주기 위해 살펴보는 과정
missing = df.isnull().sum() # 각 컬럼별 결측치를 계산한다.
missing = missing[missing > 0].sort_values(ascending=True)

# ======== 시각화 ========
# 막대형 그래프 : 컬럼별 결측치 개수
px.bar(x=missing.values, y=missing.index, orientation='h',
       title='결측치 개수', text=missing.values,
       color=missing.values, color_continuous_scale='Reds',
       labels={'x':'결측치 수','y':'컬럼명'}).show()

# 구매 여부 분포 확인 하기
# 타깃 값이 한쪽으로 치우쳐진건 아닌지 확인하기 위해 살펴보는 과정
cnt = df['ProdTaken'].value_counts().rename(index={0:'미구매(0)',1:'구매(1)'})


# 시각화 (파이 차트) : 구매 여부 분포
fig2 = px.pie(names=cnt.index, values=cnt.values, title='구매 여부 분포',
              color_discrete_sequence=['lightblue','salmon'], hole=0.3)
fig2.update_traces(textinfo='label+percent+value')
fig2.show()


# 직업별 구매율을 살펴본다. (중요한 피쳐인지 아닌지 확인한다.)
# 막대형 그래프 : 직업별 구매율
fig3 = px.bar(occ, x='구매율', y='직업', orientation='h',
              title='직업별 구매율',
              text=[f'{v:.1%}' for v in occ['구매율']],
              color_discrete_sequence=['royalblue'])
fig3.update_traces(textposition='outside')
fig3.show()

"""---
## 3단계. 전처리 준비

**새 변수 추가**: `TotalVisitors`(총 방문 인원), `HighIncome`(고소득 여부)

| 컬럼 타입 | 결측치 처리 | 변환 |
|-----------|------------|------|
| 숫자형 | 중앙값으로 대체 | 표준화 |
| 범주형(문자) | 최빈값으로 대체 | 원-핫 인코딩 |
"""

# 파생 변수 추가 (원래 없던 컬럼)

# 총 방문 인원 추가
df['NumberOfChildrenVisiting'] = df['NumberOfChildrenVisiting'].fillna(0) # 동반 자녀 수가 비어 있으면 0으로 채움
df['TotalVisitors'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting'] # 총 방문 인원 수를 보기 위해 새 변수를 만듦 (방문인원 + 동반 자녀수)
# 월소득이 중앙값 이상이라면 1 , 아니라면 0
# 중앙값 ex.) 1 ~ 1000 중앙값 은 500.5

# 고소득 여부 변수 추가
df['HighIncome']    = (df['MonthlyIncome'] >= df['MonthlyIncome'].median()).astype(int)

# 문제 x 와 / 정답(label) y 를 나눔 .
X = df.drop(columns=['CustomerID','ProdTaken']) # 고객 ID와 구매여부 를 제외
# 이유 : 고객 아이디는 예측에 도움이 되지 않아서, 구매여부는 정답(y)이기 때문에 입력에서 제외한다.

y = df['ProdTaken'] # 구매 여부를 정답(y)으로 설정

# 데이터를 학습용(80%)과 테스트용(20%)으로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f'학습: {X_train.shape[0]}명 / 테스트: {X_test.shape[0]}명')

# 숫자형 컬럼과 범주형 컬럼 분리
num_cols = X_train.select_dtypes(include='number').columns.tolist()
cat_cols = X_train.select_dtypes(exclude='number').columns.tolist()

# 숫자형 / 범주형은 전처리 방법이다르다.
# 숫자데이터는 표준화
# 문자데이터는 원핫 인코딩 방식을 사용하여야 한다.

# 숫자형: 빈 값 -> 중앙값 -> 표준화
num_pipe = Pipeline([('imputer',SimpleImputer(strategy='median')),('scaler',StandardScaler())])
# 범주형: 빈 값 -> 최빈값 -> 원-핫 인코딩(문자를 0/1로)
cat_pipe = Pipeline([('imputer',SimpleImputer(strategy='most_frequent')),('onehot',OneHotEncoder(handle_unknown='ignore'))])

# 전처리 된 숫자형, 범주형 데이터를 하나로 합침.
preprocessor = ColumnTransformer([('num',num_pipe,num_cols),('cat',cat_pipe,cat_cols)])
print('전처리 준비 됨')
