# -*- coding: utf-8 -*-
"""task1_divide_conquer_merge_sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHsFjJxe335NaIIXzSn_xMsfSkV0LAqk
"""

import random   # 대규모의 테스트 데이터 생성
import time # 실행시간을 측정한다. (성능 분석)
from typing import List # 입력 받을때의 타입은 리스트로 명시해 힌트를 준다.
# divide : 문제를 작은 문제로 나눈다.
# conquer : 길이 1까지 분할 된 배열은 이미 정렬된 상태로 간주한다.
# combine : 정렬된 부분배열을 merge 함수를 사용하여 결과를 병합하여 문제 해결
# 원본을 직접 바꾸지 않는다. 정렬된 결과를 새로 만들어 반환한다.
# 큰 문제를 작은 문제로 계속 나누고 , 작은 문제의 결과들을 합치는 방식.
def merge_sort(arr: List[int]) -> List[int]:
# 종료조건
# 원소가 1개이면 이미 정렬 된 상태. 더 나누기 불가 . 재귀 종료
    if len(arr) <= 1:
        return arr
    # divide (절반으로 분할 한다.)
    mid = len(arr) // 2 # 리스트 가운데 인덱스를 구한다.
    # 분할정복 (각각 반으로 나누기 반복)
    left = merge_sort(arr[:mid])    # 왼쪽 절반 재귀 호출
    right = merge_sort(arr[mid:])   # 오른쪽 절반 재귀 호출
    # 정렬이 된 배열 을 합친다.
    return merge(left, right)