# -*- coding: utf-8 -*-
"""adaboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSBbDqhlNDqMYurIN5rFFUQOau86v5z7
"""

# 데이터 셋 다운로드
!wget https://archive.ics.uci.edu/static/public/240/human+activity+recognition+using+smartphones.zip
!unzip human+activity+recognition+using+smartphones.zip

# 압축풀기
!unzip "UCI HAR Dataset.zip"

# 이동
!mv "human_activity/UCI HAR Dataset" "UCI HAR Dataset"

# 복사
!cp "UCI HAR Dataset/features.txt" "UCI HAR Dataset/train/features.txt"

import os
os.listdir()

# adaboost
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

# 데이터셋을 구하는 함수 설정
def get_human_dataset():
  # 각 데이터 파일들은 공백으로 분리되어 있으므로 read_csv에서 공백문자를 sep 으로  할당
  feature_name_df = pd.read_csv('UCI HAR Dataset/train/features.txt', sep = '\s+',
                                header = None, names = ['column_index', 'column_name'])
  # 데이터프레임에 피쳐명을 컬럼으로 부여하기 위해 리스트 객체로 다시 반환
  feature_name = feature_name_df.iloc[:, 1].values.tolist()

  # 학습 피처 데이터세트와 테스트 피쳐 데이터를 데이터 프레임으로 로딩
  # 컬럼명은 feature_name 적용
  X_train = pd.read_csv('UCI HAR Dataset/train/X_train.txt' , sep = '\s+', names = feature_name)
  X_test = pd.read_csv('UCI HAR Dataset/test/X_test.txt', sep = '\s+', names = feature_name)

  # 학습 레이블과 테스트 레이블 데이터를 데이터 프레임으로 로딩, 컬럼명은 action 으로 부여
  y_train = pd.read_csv('UCI HAR Dataset/train/y_train.txt', sep = '\s+', names = ['action'])
  y_test = pd.read_csv('UCI HAR Dataset/test/y_test.txt', sep = '\s+', names =['action'])

  # 로드된 학습 / 테스트용 데이터프레임을 모두 반환
  return X_train, X_test, y_train, y_test

# 학습/테스트용 데이터 프레임 반환
X_train, X_test, y_train, y_test = get_human_dataset()

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

clf = AdaBoostClassifier(n_estimators=30,
                         random_state= 10,
                         learning_rate=0.1)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
print('Ada boost 정확도 : {:.4f}'.format(accuracy_score(y_test, pred)))
# Ada boost 정확도 : 0.5310 수치가 다름 / 경로를 움직이면서 문제가 생긴건지, 버젼 이슈인지 확인 필요

!mkdir -p human_activity/train human_activity/test
!cp "UCI HAR Dataset/features.txt" human_activity/features.txt
!cp "UCI HAR Dataset/train/X_train.txt" human_activity/train/X_train.txt
!cp "UCI HAR Dataset/train/y_train.txt" human_activity/train/y_train.txt
!cp "UCI HAR Dataset/test/X_test.txt" human_activity/test/X_test.txt
!cp "UCI HAR Dataset/test/y_test.txt" human_activity/test/y_test.txt

# 현재 버전 1.6.1
import sklearn
print(sklearn.__version__)
print(X_train.shape, X_test.shape)
print(y_train['action'].value_counts().sort_index())

# 출력 결과 다름 버젼 이슈로 다운그레이드 진행
!pip -q install scikit-learn==1.5.2

# 재시작
import os, sys
os.kill(os.getpid(), 9)

# 다운그레이드 버전 재확인 1.5.2
import sklearn
print(sklearn.__version__)

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

clf = AdaBoostClassifier(n_estimators=30,
                         random_state= 10,
                         learning_rate=0.1)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
print('Ada boost 정확도 : {:.4f}'.format(accuracy_score(y_test, pred)))

"""# ADA 알고리즘

틀린 데이터를 다시 전체 학습하는 것이 아니라,


이전 모델이 틀린 데이터의 중요도(weight)를 높여


다음 모델이 그 데이터를 더 많이 보도록 학습 방식을 조정하는 알고리즘이다.
"""