# -*- coding: utf-8 -*-
"""CrossValidation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMEk-HU4UjvF-OqbiTK2ZoO2AN9v7zOB
"""

import sklearn
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 분할 단계
iris = load_iris()# train 70% test 30% 분할
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3, random_state= 1)
dt_clf = DecisionTreeClassifier(random_state=1) # 딕션 트리생성 , 결과 고정
dt_clf.fit(X_train, y_train)  # 학습
pred = dt_clf.predict(X_test) # 테스트 데이터 예측
round(accuracy_score(y_test, pred), 4)  # 정확도 계산

# k-fold 교차검증
# 데이터를 k 개의 fold 로 나누어 k 번 반복 검증
from sklearn.model_selection import KFold
kfold = KFold(n_splits = 5) # 데이터를 5 등분 한다. 5번 반복 검증

iris = load_iris()
feature = iris.data # 입력 feature
label = iris.target # 정답 label

cv_accuracy = []  # fold 의 정확도를 저장할 list
n_iter = 0  # 몇 번째 fold 인지 count
dt_clf = DecisionTreeClassifier(random_state=1)
feature.shape

n_iter = 0  # 카운터 초기화
  # kfold.split(feature): 각 폴드의 학습/검증 인덱스를 순서대로 반환
for train_index, test_index in kfold.split(feature):
  # 피처 분할
  x_train, x_test = feature[train_index], feature[test_index]
  # 레이블 분할
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(x_train, y_train)  # 학습
  pred = dt_clf.predict(x_test) # 예측
  n_iter += 1 # 폴드 카운터 증가
  # 폴드 정확도
  accuracy = np.round(accuracy_score(y_test,pred), 4)
  # 학습데이터 개수
  train_size = x_train.shape[0]
  # 검증데이터 개수
  test_size = x_test.shape[0]

  print('\n{0} 교차 검증 정확도 : {1}, 학습 데이터 크기: {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy) # 정확도 리스트에 추가

print('\n## 평균 검증 정확도 : ', np.mean(cv_accuracy)) # 낮은 폴드 존재

# iris → DataFrame 로 변환
iris_df = pd.DataFrame(data = iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target  # 레이블 컬럼 추가
iris_df # 출력확인

kfold = KFold(n_splits=3) # 3등분
n_iter_ = 0

for train_index, test_index in kfold.split(iris_df):
    n_iter_ += 1
    # iloc : 정수 인덱스로 행 선택
    train = iris_df['label'].iloc[train_index] # 학습 레이블
    test = iris_df['label'].iloc[test_index] # 검증 레이블

    print('# 교차 검증 :{}'.format(n_iter_))
    print('# 학습 레이블 데이터 : \n', train.value_counts())  # 클래스별 개수
    print('# 검증 레이블 데이터 : \n', test.value_counts())
# 교차 검증 :1
# 학습 레이블 데이터 :
#  label
# 1    50
# 2    50
# 학습 데이터에는 label 0 이없었음.

# 검증 레이블 데이터 :
#  label
# 0    50
# 검증데이터는 레이블 0 이 나타남..

# 교차 검증 :2
# 학습 레이블 데이터 :
#  label
# 0    50
# 2    50
#-- 학습데이터 0, 2 는 있는데 1 이 없음...

# Name: count, dtype: int64
# 검증 레이블 데이터 :
#  label
# 1    50
# -- 테스트 하는데 학습하지 않은 레이블 1 이 나옴

# 어떤 시험을 보는지 알려주지 않고 갑자기 시험 본 것 과 같음
# 0,2 번 만 공부했는데 배우지 않은 1번 만 나왔음 . 1번 문제 풀어봐

# 이런 현상이 생기는 이유 : 데이터를 랜덤하게 나누지 않고, 차례대로 클래스 순서대로 잘라버려서 생긴 문제
# shuffle=True를 사용하거나, 분류 문제에서는 StratifiedKFold를 사용하는 것이 더 적절하다.

# 사용하는 이유 : 운 방지 ..(편향 줄이기) 80% 학습 20% 테스트 한 경우 ..
# 쉬운문제들만 테스트 데이터에 들어간 경우 : 성능 좋은것으로 판단.
# 어려운문제들만 테스트 데이터에 들어간 경우 : 성능이 안좋은 모델로 판단.

# 3fold, 5fold... 같은 모델로 시험 3번 , 5번 .... 보기
# 여러번 시험을 봐서 진짜 실력을 본다.  (컨디션 안좋은날, 컨디션 최상의 날 등..)

# 3 fold
kfold = KFold(n_splits=3) # 데이터 3등분
n_iter = 0  # 몇번쨰 교차검증인지 카운트
# train / test 인덱스 받기
for train_index, test_index in kfold.split(feature):
  # 데이터 쪼개기
  x_train, x_test = feature[train_index], feature[test_index]
  y_train, y_test = label[train_index], label[test_index]
# 딕션 트리 모델로 학습하고
  dt_clf.fit(x_train, y_train)
  # 예측값 생성
  pred = dt_clf.predict(x_test)
  # 카운트 1 (폴드 번호 추가)
  n_iter += 1
  # 정확도 계산 소수 정답과 예측 비교 / 소수4쨰자리 까지 반올림(round)
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = x_train.shape[0] #행(샘플) 개수
  test_size = x_test.shape[0]

  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  # 정확도 저장
  cv_accuracy.append(accuracy)

  # 소수점 4째자리 반올림. → 정확도 자체가 0.0 이기 때문에 티가 안남.
  # 기본분할 + 클래스 정렬 때문

# 계층별 k - 겹 교차 검증기법

# 비율을 동일하게 유지하면서 데이터를 나누는 교차검증
from sklearn.model_selection import StratifiedKFold
S_kfold = StratifiedKFold(n_splits=5)

cv_accuracy = []  # 폴드 정확도 저장 리스트
n_iter = 0  # 폴드 카운트 0
# StratifiedKFold는  클래스 비율 유지를 위해 label 을 함께 전달 해줘야 한다.
# StratifiedKFold는 매 fold마다 클래스 비율을 유지해서 train/test를 만들어줌.
for train_index, test_index in S_kfold.split(feature, label):
  # 데이터 쪼개기
  x_train, x_test = feature[train_index], feature[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(x_train, y_train)  # 학습
  pred = dt_clf.predict(x_test) # 예측
  n_iter += 1 # 폴드번호 증가
  # 정확도 계산 4째자리 반올림
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = x_train.shape[0]
  test_size = x_test.shape[0]


  print('\n{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))

# 매 fold마다 클래스 비율을 유지해서 나눔
# 각 fold에 클래스 비율이 전체 데이터와 비슷하게 유지된다
# 안정적인 모델 평가가 가능하다.

skfold_1 = StratifiedKFold(n_splits=5)  # 데이터 5개 폴드 로 나눔. (각 fold 마다 클래스 비율을 유지)
n_iter_=0 # 교차검증 횟수

# 첫번째 파라미터 (데이터 x, label y )
# y(label) 를 기준으로 계층분할 수행
for train_index, test_index in skfold_1.split(iris_df, iris_df['label']):
  n_iter_+= 1 # 폴드 번호 증가
  # 모델학습x 클래스 비율이 잘 유지 되는지 확인 하기 위해서
  train = iris_df['label'].iloc[train_index]
  test = iris_df['label'].iloc[test_index]
  # 클래스 개수 출력하기 (목표 : 비율이 잘 유지가 되는지 확인)
  print("# 교차 검증:{}".format(n_iter_))
  print("# 학습 레이블 데이터 : \n", train.value_counts())
  print("# 검증 레이블 데이터 : \n", test.value_counts())

# LOOCV(Leave - One - Out Cross- Validation)
# 데이터 1개만 테스트로 쓰고 나머지 전부를 학습에 사용하는 교차검증
from sklearn.model_selection import LeaveOneOut, cross_val_score

iris = load_iris()
feature = iris.data
label = iris.target
# train 149개 / test 1개
dt_clf = DecisionTreeClassifier(random_state = 1)
loocv = LeaveOneOut()
# 데이터 개수(150개)만큼 반복 수행 → 교차 검증 횟수 = 150
score = cross_val_score(dt_clf, feature, label, cv = loocv)

print('\n## 교차 검증 횟수 :', len(score))  # 150
print('\n## 평균 검증 정확도 :', round(np.mean(score),4)) # 거의 모든 데이터를 학습에 사용해서 편향(bias)이 낮다.

# 좋은점 : 편향이 낮다.
# 나쁜점 : 계산량이 많다.
# 데이터 개수 만큼 학습해야해서 계산량이 많아 실무에서는 많이 안쓰일것 같다.



print('\n## 교차 검증 횟수 :', len(score))
print('\n## 평균 검증 정확도 :', round(np.mean(score),4))

# 반복 교차 검증기법
from sklearn.model_selection import RepeatedStratifiedKFold

iris = load_iris()
feature = iris.data # x : 학습데이터
label = iris.target # y : 정답데이터
dt_clf = DecisionTreeClassifier(random_state=1) # 딕션트리 모델 생성 , 난수고정
# 디폴트 값 저장이 되어있음.:  n_splits=5, n_repeats=10

# 5개의 폴드를 교차검증 10 번 반복 수행

# RepeatedStratifiedKFold 생성
rskfold = RepeatedStratifiedKFold()
score = cross_val_score(dt_clf, feature, label, cv = rskfold)

print('\n## 교차 검증 횟수 : ', len(score)) # 50
print('\n## 평균 검증 정확도 : ', round(np.mean(score),4))


# 좋은점 : 매번 다른 데이터 분할로 교차검증을 반복하여 평가의 신뢰도를 높인다.(운좋게 푼거 아님.)

