# -*- coding: utf-8 -*-
"""bin_pre_in_post.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZ4uVeUi3V-yX3_iEzSxp9ey4zgtE4D6
"""

# 노드 클래스 정의
class Node:
    def __init__(self, value):
        self.value = value  # 노드가 담고 있는 데이터
        self.left = None  # 왼쪽 자식 노드
        self.right = None  # 오른쪽 자식 노드


# 이진트리 클래스 정의 (queue 사용)
class BinaryTree:
    def __init__(self):  # 초기화
        self.root = None  # 트리 최상단 노드(root)

    def insert(self, value):  # 값 추가
        new_node = Node(value)
        if self.root is None:
            self.root = new_node
            return

        queue = [self.root]
        while queue:
            current = queue.pop(0)  # 큐에서 노드 꺼내기
            if current.left is None:
                current.left = new_node  # 왼쪽 자리에 삽입
                return
            else:
                queue.append(current.left)

            if current.right is None:
                current.right = new_node  # 오른쪽 자리에 삽입
                return
            else:
                queue.append(current.right)

    #
    #          1
    #        /   \
    #       2     3
    #      / \   / \
    #     4   5 6   7
    #

    # 차이점 :
    # 전위 (Preorder) : Root > L > R    / 1, 2, 4 ,5, 3, 6, 7
    # 중위 (Inorder) : L > Root > R     / 4, 2, 5, 1, 6, 3, 7
    # 후위 (Postorder) : L > R > Root   / 4, 5, 2, 6, 7, 3, 1

    # 전위순회 root > left > right
    def preorder(self, node, result=None):
        if result is None:
            result = []

        if node:
            result.append(node.value)  # 1. 현재 노드 방문
            self.preorder(node.left, result)  # 2. 왼쪽 서브트리
            self.preorder(node.right, result)  # 3. 오른쪽 서브트리
        return result

    # 중위순회 left > root > right
    def inorder(self, node, result=None):
        if result is None:
            result = []
        if node:
            self.inorder(node.left, result)  # 1. 왼쪽 서브트리
            result.append(node.value)  # 2. 현재 노드 방문
            self.inorder(node.right, result)  # 3. 오른쪽 서브트리
        return result

    # 후위순회 left > right > root
    def postorder(self, node, result=None):
        if result is None:
            result = []

        if node:
            self.postorder(node.left, result)  # 1. 왼쪽 서브트리
            self.postorder(node.right, result)  # 2. 오른쪽 서브트리
            result.append(node.value)  # 3. 현재 노드 방문
        return result


tree = BinaryTree()
for value in [1, 2, 3, 4, 5, 6, 7]:
    tree.insert(value)

print(tree.preorder(tree.root))  # [1, 2, 4, 5, 3, 6, 7]
print(tree.inorder(tree.root))  # [4, 2, 5, 1, 6, 3, 7]
print(tree.postorder(tree.root))  # [4, 5, 2, 6, 7, 3, 1]