# -*- coding: utf-8 -*-
"""lcm_gcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZ4uVeUi3V-yX3_iEzSxp9ey4zgtE4D6
"""

# 최대공약수 (GCD) - 유클리드 알고리즘
# 유클리드 알고리즘 = "큰 수를 작은 수로 나눈 나머지로 계속 교체하면 결국 GCD(최대 공약수)가 나온다"


# 나머지가 없어질 때까지 숫자를 계속 줄이기
def gcd(a, b):  # a, b 입력 받음. 두 숫자의 최대공약수 구하기
    while b:  # b가 0이 될 때까지 반복  (나머지 나옴)
        a, b = b, a % b  # a에 b를, b에 나머지를 대입   (안 나눠 질때까지)
        # 숫자를 점점 작게 줄여가며 공통 약수를 찾는 과정
    return a  # b가 0이 되면 a가 최대공약수


# 최소공배수 (LCM)
def lcm(a, b):  # a, b의 최소공배수 구하기
    return a * b // gcd(a, b)  # LCM = a * b / GCD(a, b) GCD 를 이용해서 구해야함.


# 결과 확인
# 최대공약수
print(gcd(12, 8))  # 4
print(gcd(48, 18))  # 6
print(gcd(100, 75))  # 25
# 최소공배수
print(lcm(12, 8))  # 24
print(lcm(48, 18))  # 144
print(lcm(100, 75))  # 300