# -*- coding: utf-8 -*-
"""printer_queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZ4uVeUi3V-yX3_iEzSxp9ey4zgtE4D6
"""

# 큐를 이용하여 프린터 작업 시뮬레이션
from collections import deque


class PrinterQueue:
    def __init__(self):  # 초기화
        self.queue = deque()  # 작업 대기열 (queue)

    def add_job(self, job):  # 작업추가 (enqueue)
        # 큐의 뒤쪽에 작업 을 추가
        self.queue.append(job)
        print(f"[추가] '{job}' 작업이 대기열에 추가 되었습니다.")

    def process(self):  # 작업 처리 (dequeue)
        # 큐가 비어있으면 , 처리할 작업이 없음
        if not self.queue:
            print("처리할 작업이 없습니다.")
            return

        job = self.queue.popleft()  # 큐 앞에서 작업 꺼내기 (FIFO)
        print(f"[출력] '{job}' 작업을 처리합니다.")
        # 처리된 작업 반환 (로그)
        return job

    # 큐가 빌 때 까지 반복 (모든 작업은 순차 처리.)
    def process_all(self):  # 전체 작업 처리
        print("\n--- 프린터 작업 시작 ---")
        while self.queue:
            self.process()
        print("--- 모든 작업 완료 ---\n")

    def status(self):  # 대기열 상태 확인
        # 큐에 작업이 남이있는 경우
        if self.queue:
            # deque > list 변환 출력 .
            print(f"대기 중인 작업: {list(self.queue)}")
        else:
            # 대기열이 빈 상태
            print("대기 중인 작업이 없습니다.")


# ===============검증==================
# 프린터 객체생성
printer = PrinterQueue()
# 작업등록
printer.add_job("문서A")
printer.add_job("문서B")
printer.add_job("문서C")

printer.status()  # 대기열 상태
printer.process_all()  # 모든 작업 순차적출력
printer.status()  # 완료 후 상태 확인